fix for job description
topcoder-platform/community-app pull request #5011
Opened 2020-09-28 13:53 UTC by skyhit

Fix for #4659

2020-09-29 03:34 UTC, luizrrodrigues requested changes

2020-09-29 03:34 UTC, luizrrodrigues commented on package-lock.json
> +    "fast-safe-stringify": {
@skyhit No changes to `package.json`, so please remove changes to `package-lock.json`

2020-09-29 03:34 UTC, luizrrodrigues commented on src/shared/components/Settings/Profile/Work/index.jsx
> +/* eslint-disable react/jsx-boolean-value */
Instead add `eslint-disable react/jsx-boolean-value`, please update:

`joinValues={true}`
to
`joinValues`

2020-09-30 15:29 UTC, skyhit commented
@luizrrodrigues changes made

2020-09-30 22:39 UTC, luizrrodrigues approved these changes

2020-11-05 13:04 UTC, closed without merging