issue 5071 fix
topcoder-platform/community-app pull request #5111
Opened 2020-10-15 17:01 UTC by PrakashDurlabhji

2020-10-15 20:10 UTC, luizrrodrigues commented
@PrakashDurlabhji Please to right branch `bug-bash`

2020-10-15 20:17 UTC, luizrrodrigues requested changes

2020-10-15 20:17 UTC, luizrrodrigues commented on src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
> +              status: 'Active',
When click in Clear Filters, status need change to `All`

2020-10-15 20:21 UTC, PrakashDurlabhji commented
@luizrrodrigues updated

2020-10-15 21:03 UTC, luizrrodrigues requested changes
https://github.com/topcoder-platform/community-app/issues/5071#issuecomment-709588671

2020-10-15 23:46 UTC, PrakashDurlabhji commented
@luizrrodrigues updatd

2020-10-16 03:42 UTC, luizrrodrigues approved these changes

2020-10-16 03:44 UTC, merged