feature:link-thrive add sidebar link to thrive article
topcoder-platform/community-app pull request #5684
Opened 2021-09-03 02:45 UTC by dedywahyudi

cc @Oanh-and-only-Oanh 

Adding new link to the sidebar

![Screen Shot 2021-09-03 at 09 28 54](https://user-images.githubusercontent.com/4476442/131942814-360ead20-e161-4f29-b7a6-b5b081bb99f2.png)

2021-09-04 11:48 UTC, dedywahyudi commented
<img width="1304" alt="Screen Shot 2021-09-04 at 10 18 42" src="https://user-images.githubusercontent.com/4476442/132093416-5aff2cdc-fbad-4b6a-8ba7-6697a67970c2.png">

2021-09-09 04:13 UTC, luizrrodrigues commented
@dedywahyudi Can you link the issue from this one please?

2021-09-09 05:39 UTC, luizrrodrigues requested changes

2021-09-09 05:39 UTC, luizrrodrigues commented on src/shared/components/challenge-detail/Specification/SideBar/index.jsx
> +            <a href="https://www.topcoder.com/thrive/articles/all-about-topcoder-challenges-tasks-and-gig-work-opportunities">
@dedywahyudi we need to use config var to point this link to right env, like Dev, Stag, etc.

ex. `config.URL.COMMUNITY`

2021-09-09 11:36 UTC, luizrrodrigues approved these changes

2021-09-09 11:52 UTC, merged