PM-199, PM-209 Denial of service fix
topcoder-platform/community-app pull request #7022
Opened 2024-12-18 13:05 UTC by hentrymartin

## What's in this PR?

- Used promised based fs functions for getting file content
- Also checking for file size and checking if the path exists

2025-01-06 23:22 UTC, jmgasper requested changes

2025-01-06 23:22 UTC, jmgasper commented on src/server/index.js
> +    const MAX_FILE_SIZE = 10 * 1024; // 10 KB max file size
Can we put this out to an env variable and default it in `config/default.js` please?

2025-01-06 23:22 UTC, jmgasper commented on src/server/services/communities.js
> +        const MAX_FILE_SIZE = 1 * 1024 * 1024; // 1 MB
Same here - can we make this configurable with a default in `config/default.js` please?

2025-01-09 16:04 UTC, hentrymartin commented
@jmgasper Can you please approve this PR, if there are no more comments to be resolved?

2025-01-09 16:39 UTC, kkartunov approved these changes

2025-01-09 19:29 UTC, jmgasper commented on src/server/index.js
> +    const MAX_FILE_SIZE = 10 * 1024; // 10 KB max file size
No, not right now - it's fine to leave this as is.

2025-01-09 19:29 UTC, jmgasper approved these changes

2025-01-10 21:59 UTC, merged